### ISSUE TITLE
API endpoints ? 

### ISSUE THREAD

**Issue by ingouackaz** [Girbons/mangarock#3]
Hello, I would like to test your API to build an mangas reader app.

However I don't understand how your API works.

Do you have informations concerning all the endpoints of API of Mangas Rock http://api.mangarockhd.com/query/web401/

Thank you very much ! :)

**Comment by Girbons** [comment]
Hi @Ze-ro-G,

This library is an unofficial wrapper around the mangarock API, for more info I suggest you to contact the mangarock support.

If it helps the endpoints that I discovered are the following:

```
- (GET) http://api.mangarockhd.com/query/web401/info?oid=
- (GET) http://api.mangarockhd.com/query/web401/pages?oid=
- (POST) http://api.mangarockhd.com/query/web401/mrs_search
```
